### ISSUE TITLE
AAC Audio codec issues due to outdated Handbrake

### ISSUE THREAD

**Issue by haldi4803** [coppit/docker-handbrake#3]
Hi,
version 1.0.4 uses a broken AAC (avcodec) which produces horrible sound quality on 160kbits.
You think you could update Handbrake to version 1.0.7 ?

**Comment by haldi4803** [comment]
Okay.... 1.0.4 is the up to date version for Handbrake on Ubuntu....
https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-releases
sorry -.-

**Comment by coppit** [comment]
FYI, I'm about to push a container for 1.1.10.
