### ISSUE TITLE
permission of folder /media

### ISSUE THREAD

**Issue by haldi4803** [coppit/docker-handbrake#4]
Hi,
I tried this Container on my Synology NAS. But handbrake always gave the error unable to read folder.
So i had to login via Console and chmod 777 /media, using 755 showed all the files but did not let handbrake write anything.
There seems to be something wrong with the Permissions for folder /media and the user that runs Handbrake.

**Comment by coppit** [comment]
I did some work to fix a permissions bug. Please set USER_ID and GROUP_ID in the config, and try again. Let me know if the issue persists.

**Comment by coppit** [comment]
Closing due to lack of response. Please reopen if the bug is still there.
