### ISSUE TITLE
Black Screen Instead of UI

### ISSUE THREAD

**Issue by stalinCCCP415** [coppit/docker-handbrake#5]
I am getting a black screen after selecting the Handbrake module in the xrdp popup. It goes through the connection messages and then I am dropped to a black screen.

USE_UI=true is in the config file.

**Comment by jason-bean** [comment]
I have the distinct feeling that this feature wasn't fully tested before he pushed it out. Looking at the run script for "handbrake-ui" it unrecoverably deletes itself if USE_UI is NOT set to exactly "yes". Even after having it set to "yes" it doesn't work complaining that XDG_RUNTIME_DIR is not set and keeps trying execute. I'm assuming that XDG_RUNTIME_DIR isn't available from a runsv service.

**Comment by coppit** [comment]
These are two separate issues. The first was fatal. The second was non-fatal. Both have been fixed.
